services:
  demo-otel-opensearch-api:
    build:
      context: ../../
      dockerfile: DemoOtelOpenSearch.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OpenTelemetry__gRPCEndpoint=http://opentelemetry-collector:4317
      - OpenTelemetry__HttpEndpoint=http://opentelemetry-collector:4318
      - SayHelloAPI=http://demo-otel-opensearch-api/weatherforecast/hello

  demo-otel-opensearch-worker:
    build:
      context: ../../
      dockerfile: DemoOtelOpenSearch.Worker/Dockerfile
    depends_on:
      - demo-otel-opensearch-api
    environment:
      - DemoOtelOpenSearchAPI=http://demo-otel-opensearch-api/weatherforecast
  
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - /config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
  
  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "2020:2020"

#  data-prepper:
#    platform: linux/amd64
#    image: opensearchproject/data-prepper:latest
#    ports:
#      - 4900:4900
#    volumes:
#      - /config/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
#      - /config/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - cluster.name=opensearch
      - node.name=opensearch
      # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      # must be a string with no spaces when specified as an environment variable
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'

volumes:
  opensearch-data:
    driver: local
