services:
  demo-otel-opensearch:
    build:
      context: .
      dockerfile: DemoOtelOpenSearch/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
        
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  data-prepper:
    platform: linux/amd64
    image: opensearchproject/data-prepper:latest
    ports:
      - 4900:4900
    volumes:
      - ./pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml

  opensearch:
    image: opensearchproject/opensearch:2.4.0
    environment:
      - discovery.type=single-node
    volumes:
      - opensearch-data:/usr/share/opensearch/data
#      - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml

    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.4.0
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      # must be a string with no spaces when specified as an environment variable
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'

volumes:
  opensearch-data:
    driver: local