services:
  demo-otel-opensearch-api:
    build:
      context: ../../
      dockerfile: DemoOtelOpenSearch.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OpenTelemetry__gRPCEndpoint=http://opentelemetry-collector:4317
      - OpenTelemetry__HttpEndpoint=http://opentelemetry-collector:4318
      - SayHelloAPI=http://demo-otel-opensearch-api/weatherforecast/hello

  demo-otel-opensearch-worker:
    build:
      context: ../../
      dockerfile: DemoOtelOpenSearch.Worker/Dockerfile
    depends_on:
      - demo-otel-opensearch-api
    environment:
      - DemoOtelOpenSearchAPI=http://demo-otel-opensearch-api/weatherforecast
  
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
