log-pipeline:
  source:
    http:
      # Explicitly disable SSL
      ssl: false
      # Explicitly disable authentication
      authentication:
        unauthenticated:
      # The default port that will listen for incoming logs
      port: 2021
  sink:
    - opensearch:
        hosts: ["http://opensearch-node1:9200"]
        index: app-logs-%{yyyy.MM.dd}
        insecure: true