extensions:
  health_check:
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
          max_age: 7200
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  otlphttp:
    endpoint: http://fluentbit:4318
    tls:
      insecure: true
    compression: none
    
#  otlp/data-prepper:
#    endpoint: data-prepper:21890
#    tls:
#      insecure: true
#  otlp/data-prepper-metric:
#    endpoint: data-prepper:21891
#    tls:
#      insecure: true
  logging:
    loglevel: debug
processors:
  batch:
service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]
#      exporters: [logging]    
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp/data-prepper, logging]
      # exporters: [logging]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [otlp/data-prepper-metric, logging]
      # exporters: [logging]

