receivers:
  otlp:
    protocols:
      http:
      grpc:
processors:
  batch:        
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]    
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, sentry]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
